# Generated by Django 4.2.2 on 2023-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folvika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('place', models.CharField(default='', max_length=35)),
                ('price', models.CharField(default='', max_length=35)),
                ('image', models.ImageField(default='', upload_to='')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
