# Generated by Django 4.2.2 on 2023-07-04 07:05

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folvika',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.getFileName),
        ),
    ]
