# Generated by Django 4.2.2 on 2023-07-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='Country',
            field=models.CharField(choices=[('INDIA', 'india'), ('SRILANKA', 'srilanka')], default='', max_length=20),
        ),
    ]
