# Generated by Django 4.2.2 on 2023-07-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_reserve_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reserve',
            new_name='reserv',
        ),
    ]
