# Generated by Django 4.2.2 on 2023-07-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_reserve_reserv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reserv',
            new_name='reserve',
        ),
    ]
