# Generated by Django 4.2.2 on 2023-07-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_reserve_hotelname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='hotelname',
            new_name='Hotelname',
        ),
    ]
