# Generated by Django 4.2.3 on 2023-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_hotelname_reserve_hotelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotelname', models.CharField(default='', max_length=35)),
                ('Firstname', models.CharField(default='', max_length=20)),
                ('Lastname', models.CharField(default='', max_length=20)),
                ('Mail', models.EmailField(default='', max_length=30)),
                ('Mobile', models.IntegerField(default='')),
                ('Country', models.CharField(choices=[('INDIA', 'india'), ('SRILANKA', 'srilanka')], default='', max_length=20)),
                ('Guest', models.IntegerField(default='')),
                ('From_date', models.CharField(default='', max_length=10)),
                ('To_date', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
